### ISSUE TITLE
upip: On Linux package installation fails with OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by Teq** [micropython/micropython-lib#108]
For example:

`micropython -m upip install micropython-sqlite3`

gives following output:

```
Installing to: /home/teq/.micropython/lib/
Warning: pypi.python.org SSL certificate is not validated
Installing micropython-sqlite3 0.2.3 from https://pypi.python.org/packages/17/07/4f39d7c00eed557e765837c970040a6fbd225f418cb6de05016a32b81347/micropython-sqlite3-0.2.3.tar.gz
Traceback (most recent call last):
  File "upip.py", line 285, in <module>
  File "upip.py", line 278, in main
  File "upip.py", line 202, in install
  File "upip.py", line 192, in install
  File "upip.py", line 162, in install_pkg
  File "upip.py", line 88, in install_tar
  File "upip.py", line 49, in _makedirs
  File "upip.py", line 48, in _makedirs
  File "upip.py", line 44, in _makedirs
OSError: [Errno 2] ENOENT
```
 The problem is in `_makedirs` function, it doesn't work with absolute path returned by `get_install_path` (see my commit for details).

I did a quickfix here: https://github.com/Teq/micropython-lib/commit/443c599123b7997d6482115205d44af4c74a79b1

**Comment by pfalcon** [comment]
Thanks for the report. I fixed it a bit differently: 7e9eed98cb983fe3c66ed45faf301ffaa7437d87
