### ISSUE TITLE
collections.defaultdict MemoryError on "in" operation

### ISSUE THREAD

**Issue by dmazzella** [micropython/micropython-lib#147]
Using this code:

```
$ MICROPYPATH="$(pwd)/micropython-lib" ~/micropython/unix/micropython.exe
MicroPython v1.8.7-68-gbdcca42-dirty on 2017-01-23; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> from collections import defaultdict
>>> t = defaultdict(list)
>>> "key" not in t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c/Users/dmazzella/OneDrive/micropython/utransitions/micropython-lib/collections/defaultdict.py", line 21, in __getitem__
MemoryError: memory allocation failed, allocating 260368 bytes
>>>
```

**Comment by pfalcon** [comment]
Thanks for the report, fixed by 69b65efd7e485684b9e64c8f8264032af5fa153c.
