### ISSUE TITLE
uasyncio.loop.run_forever() — line 100, TypeError: function takes 2 positional arguments but 1 were given

### ISSUE THREAD

**Issue by stroobandt** [micropython/micropython-lib#264]
I am running into the following weird `uasyncio` error, only after the loop has executed an arbitrary number of times:

    Traceback (most recent call last):
      File "main.py", line 25, in <module>
      File "/flash/lib/my_module.py", line 328, in start
      File "/flash/lib/my_module.py", line 326, in start
      File "/flash/lib/uasyncio/core.py", line 100, in run_forever
    TypeError: function takes 2 positional arguments but 1 were given
    MicroPython v1.9.3-477-g7b0a020a on 2018-03-21; PYBv1.1 with STM32F405RG

My `start()` method is quite trivial:

    def start(self):

        try:
            self.loop.run_forever()
        except KeyboardInterrupt or SystemExit:
            sys.exit()

I have start seeing this error appearing only since I moved my class and methods to a separate `my_module.py`. Pyboard firmware and `uasyncio` are the latest versions. The seemingly random occurrence of this `/flash/lib/uasyncio/core.py` error makes it hard to debug.

**Comment by stroobandt** [comment]
The error was due to an unintentional object initialisation in the callback function of a `uasyncio.loop.call_later()`, nested within the `uasyncio.loop.run_forever()` in _my_ code.
So, no `uasyncio` bug after all.
