### ISSUE TITLE
uaiohttpclient issue: ValueError: need more than 1 values to unpack

### ISSUE THREAD

**Issue by eltomek** [micropython/micropython-lib#330]
Trying to run an example for uaiohttpclient

Official micropython with micropython-lib (both from master latest) 

```
cd micropython/ports/unix
$ ./micropython ~/src/micropython-lib/uaiohttpclient/example.py python.org
Traceback (most recent call last):
  File "/home/tomek/src/micropython-lib/uaiohttpclient/example.py", line 27, in <module>
  File "/home/tomek/.micropython/lib/uasyncio/core.py", line 180, in run_until_complete
  File "/home/tomek/.micropython/lib/uasyncio/core.py", line 154, in run_forever
  File "/home/tomek/.micropython/lib/uasyncio/core.py", line 109, in run_forever
  File "/home/tomek/.micropython/lib/uasyncio/core.py", line 177, in _run_and_stop
  File "/home/tomek/src/micropython-lib/uaiohttpclient/example.py", line 18, in run
  File "/home/tomek/src/micropython-lib/uaiohttpclient/uaiohttpclient.py", line 67, in request
  File "/home/tomek/src/micropython-lib/uaiohttpclient/uaiohttpclient.py", line 49, in request_raw
ValueError: need more than 1 values to unpack

```

**Comment by pfalcon** [comment]
Did you consider to actually go and look what happens in the lines mentioned in the traceback? This way, you can get your answers in seconds, not in days/weeks.

Here, the issue is obvious - uaiohttpclient accepts URLs as parameters, and "python.org" is not a URL.
