### ISSUE TITLE
OSError: [Errno 5] EIO, urequests error

### ISSUE THREAD

**Issue by abaouz** [micropython/micropython-lib#396]
```
>>> uos.uname()                                                                                  
(sysname='esp8266', nodename='esp8266', release='2.0.0(5a875ba)', version='v1.12-351-gbd5633778 o
n 2020-04-08', machine='ESP module (1M) with ESP8266')
```

To reproduce the bug:
import urequests
urequest.get("some url")

`ssl_handshake_status: -40                                                                        
Traceback (most recent call last):                                                               
  File "<stdin>", line 1, in <module>                                                            
  File "/lib/urequests.py", line 112, in get                                                     
  File "/lib/urequests.py", line 60, in request                                                  
OSError: [Errno 5] EIO`

Is it know bug ?

**Comment by mattytrentini** [comment]
This may be related to #400 but, in any case, it's quite old. Could you please re-test and reopen this if the problem still exists? It would also be helpful to supply the failing url if possible.
