### ISSUE TITLE
how to install micropython-lib

### ISSUE THREAD

**Issue by kirilacsl** [micropython/micropython-lib#417]
```
C:\Users\kiril>pip install git+https://github.com/micropython/micropython-lib
Collecting git+https://github.com/micropython/micropython-lib
  Cloning https://github.com/micropython/micropython-lib to c:\users\kiril\appdata\local\temp\pip-req-build-uh7e8oxj
  Running command git clone -q https://github.com/micropython/micropython-lib 'C:\Users\kiril\AppData\Local\Temp\pip-req-build-uh7e8oxj'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kiril\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kiril\\AppData\\Local\\Temp\\pip-req-build-uh7e8oxj\\setup.py'"'"'; __file__='"'"'C:\\Users\\kiril\\AppData\\Local\\Temp\\pip-req-build-uh7e8oxj\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kiril\AppData\Local\Temp\pip-pip-egg-info-ojjq9qtj'
         cwd: C:\Users\kiril\AppData\Local\Temp\pip-req-build-uh7e8oxj\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kiril\appdata\local\programs\python\python39\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kiril\\AppData\\Local\\Temp\\pip-req-build-uh7e8oxj\\setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/micropython/micropython-lib. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kirilacsl** [comment]
help pls
