### ISSUE TITLE
socket.bind(("", PORT)) fails with errors

### ISSUE THREAD

**Issue by PeterKenyon** [micropython/micropython-lib#56]
I tried the following to bind to any adapter on the unix port running on BBB

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind(("", 9090))

and I got the following error

Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "main.py", line 22, in run
  File "/root/.micropython/lib/socket.py", line 37, in bind
  File "/root/.micropython/lib/socket.py", line 15, in _resolve_addr
OSError: [addrinfo error -5]

**Comment by pfalcon** [comment]
Fixed. Though general suggestion in such cases is just use full address form ("0.0.0.0" in this case).

**Comment by PeterKenyon** [comment]
yeh I found that out, thanks
