### ISSUE TITLE
mip: package installation issues

### ISSUE THREAD

**Issue by dsliwski** [micropython/micropython-lib#692]
I just upgraded firmware to esp8266-1m-20230426-v1.20.0
and cannot install packages via mip:
```
>>> mip.install('requests')
Installing requests (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -2
>>> mip.install('urequests')
Installing urequests (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -2
>>> mip.install('micropython-urequests')
Installing micropython-urequests (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -2
>>> mip.install('micropython-requests')
Installing micropython-requests (latest) from https://micropython.org/pi/v2 to /lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mip/__init__.py", line 1, in install
  File "mip/__init__.py", line 1, in _install_package
  File "mip/__init__.py", line 1, in _install_json
  File "urequests.py", line 180, in get
  File "urequests.py", line 76, in request
OSError: -2
```

**Comment by dsliwski** [comment]
I was not connected to the network.
Connecting to the network solved the issue:
```
>>> sta.isconnected()
True
>>> mip.install('urequests')
Installing urequests (latest) from https://micropython.org/pi/v2 to /lib
Copying: /lib/urequests.mpy
Done
```
