### ISSUE TITLE
micropython/lora RuntimeError: Unexpected silicon version 0

### ISSUE THREAD

**Issue by davefes** [micropython/micropython-lib#774]
Having an issue with running micropython/lora on a 8MB WeACT Blackpill.  It runs fine from the internal flash,
using a different firmware at the website:  https://github.com/nspsck/STM32F411CEU6_BlackPill_Micropython/tree/main

On the 8MB variant:
```
Entering REPL. Use Control-X to exit.

MicroPython v1.22.0-preview.162.g6117aa686.dirty on 2023-11-19; WeAct Studio Blackpill v3.1 8MB with STM32F411CE
Type "help()" for more information.
>>> 
>>> 
MPY: sync filesystems
MPY: soft reboot
Traceback (most recent call last):
  File "main.py", line 216, in <module>
  File "main.py", line 54, in main
  File "main.py", line 47, in get_modem
  File "sx127x.py", line 267, in __init__
RuntimeError: Unexpected silicon version 0
MicroPython v1.22.0-preview.162.g6117aa686.dirty on 2023-11-19; WeAct Studio Blackpill v3.1 8MB with STM32F411CE
Type "help()" for more information.
```

When I was working on this distro:
 https://github.com/Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266/tree/master
I would sometimes get this error on the ESP32 platform, which "seemed" to be sorted by doing a manual RF96 chip reset.

I did notice that the reset low could vary from 1ms to as short as 100us, so I tried making the low and the following high for 50ms, to no avail.

In the past I have just commented-out that test, but when I do it for these 8MB boards the units do not communicate.

Seems to suggest that SPI comms to the LoRa chip differs between internal and external flash.

**Comment by davefes** [comment]
Actually, it throws the same error running the regular firmware from internal flash.  Must be a RF96 or wiring issue.
